INSERT INTO categories (category_name) VALUES
('Electronics'),
('Books'),
('Clothing'),
('Home & Kitchen'),
('Toys & Games'),
('Sports & Outdoors'),
('Beauty & Personal Care'),
('Health & Household'),
('Automotive'),
('Grocery'),
('Pet Supplies'),
('Furniture'),
('Jewelry'),
('Watches'),
('Shoes & Accessories'),
('Luggage & Travel Gear'),
('Industrial & Scientific'),
('Baby Products'),
('Musical Instruments'),
('Movies & TV Shows'),
('Video Games'),
('Software'),
('Office Products'),
('Cell Phones & Accessories'),
('Computers & Tablets'),
('Cameras & Photo'),
('Appliances'),
('Garden & Outdoor'),
('DIY Tools'),
('Food & Beverages'),
('Art & Craft'),
('Collectibles & Fine Art'),
('Fashion Accessories'),
('Underwear & Loungewear'),
('Lighting'),
('Bedding & Bath'),
('Kitchen & Dining'),
('Cleaning Supplies'),
('Office Furniture'),
('Backpacks & Bags'),
('Sunglasses'),
('Fitness & Supplements'),
('Outdoor Recreation'),
('Camping & Hiking'),
('Cycling'),
('Running'),
('Swimming'),
('Winter Sports'),
('Team Sports'),
('Golf'),
('Tennis & Racquet Sports'),
('Fishing'),
('Hunting'),
('Eco-Friendly Products'),
('Handmade Products'),
('Luxury Beauty'),
('Skincare'),
('Haircare'),
('Makeup'),
('Fragrances'),
('Men’s Grooming'),
('Women’s Health'),
('Vitamins & Supplements'),
('Medical Supplies'),
('Smart Home Devices'),
('Drones'),
('3D Printers'),
('Networking Equipment'),
('Printers & Ink'),
('Computer Components'),
('Storage & Organization'),
('Party Supplies'),
('Holiday Decorations'),
('Wedding & Party Planning'),
('Stage Lighting'),
('Audio Equipment'),
('Studio Recording'),
('Books & Literature'),
('Comics & Graphic Novels'),
('Textbooks'),
('Audiobooks'),
('Magazines'),
('Maps & Globes'),
('Education & Learning'),
('Children’s Books'),
('Test Preparation'),
('Language Learning'),
('Religious & Spirituality'),
('Cookbooks'),
('Science & Math'),
('History'),
('Business & Money'),
('Engineering'),
('Medicine'),
('Law'),
('Travel Guides'),
('Self-Help'),
('Parenting'),
('Pets'),
('Psychology'),
('Politics'),
('Biographies'),
('True Crime'),
('Mystery & Thriller'),
('Fantasy'),
('Science Fiction'),
('Romance'),
('Horror'),
('Humor'),
('Arts & Photography'),
('Design'),
('Architecture'),
('Photography'),
('Music'),
('Performing Arts'),
('Digital Music'),
('Sheet Music'),
('Concert Tickets'),
('Streaming Services'),
('Gift Cards'),
('Deals & Offers'),
('Clearance Items'),
('New Arrivals'),
('Top Rated'),
('Best Sellers'),
('Seasonal Deals'),
('Subscription Boxes'),
('Imported Goods'),
('Local Handicrafts'),
('Ethnic Wear'),
('Traditional Decor'),
('Organic Products'),
('Kids & Baby Fashion'),
('Unisex Apparel'),
('Vintage Clothing'),
('Costumes & Accessories'),
('Formal Wear'),
('Activewear'),
('Sleepwear'),
('Footwear'),
('Bags & Wallets'),
('Belts & Suspenders'),
('Eyewear'),
('Headphones & Earbuds'),
('Speakers & Soundbars'),
('Smartwatches'),
('Tablets'),
('Monitors'),
('Keyboards & Mice'),
('Chairs & Desks'),
('Desks & Workstations'),
('Storage Units'),
('Decorative Items'),
('Clocks'),
('Wall Art'),
('Rugs & Carpets'),
('Curtains & Blinds'),
('Bed Linens'),
('Pillows & Throws'),
('Bathroom Essentials'),
('Laundry Supplies'),
('Trash & Storage Bins'),
('Light Bulbs & Fixtures'),
('Power Strips & Surge Protectors'),
('Extension Cords'),
('Smart Plugs'),
('Electric Kettles'),
('Coffee Makers'),
('Blenders'),
('Microwaves'),
('Refrigerators'),
('Air Conditioners'),
('Heaters'),
('Fans'),
('Vacuum Cleaners'),
('Irons & Steamers'),
('Washing Machines'),
('Dryers'),
('Gas Grills'),
('Indoor Grills'),
('Ovens'),
('Stoves'),
('Toasters'),
('Juicers'),
('Water Purifiers'),
('Air Purifiers'),
('Humidifiers'),
('Dehumidifiers'),
('Security Cameras'),
('Smart Doorbells'),
('Locks & Alarms'),
('Thermostats'),
('Smoke Detectors'),
('Carbon Monoxide Detectors'),
('Smart Lights'),
('Robot Vacuums'),
('Lawn Mowers'),
('Pressure Washers'),
('Planters & Pots'),
('Gardening Tools'),
('Soil & Fertilizers'),
('Seeds & Plants'),
('Pest Control'),
('Garden Furniture'),
('Grills & Accessories'),
('Pool & Spa Supplies'),
('Outdoor Heating'),
('Barbecue Tools'),
('Bird Feeders'),
('Compost Bins'),
('Garden Decor'),
('Solar Lights'),
('Watering Systems'),
('Gloves & Protection'),
('Shovels & Rakes'),
('Ladders & Stands'),
('Pruning Tools'),
('Weed Control'),
('Lawn Edgers'),
('Trimmers & Shears'),
('Outdoor Speakers'),
('Gazebos & Canopies'),
('Decking Materials'),
('Garden Statues'),
('Wind Chimes'),
('Garden Flags'),
('Outdoor Clocks'),
('Fire Pits'),
('Picnic Supplies'),
('Coolers'),
('Beach Towels'),
('Umbrellas & Shades'),
('Camping Chairs'),
('Sleeping Bags'),
('Tents'),
('Camp Stoves'),
('Hiking Backpacks'),
('Navigation Tools'),
('First Aid Kits'),
('Flashlights'),
('Multi-tools'),
('Survival Gear'),
('Water Bottles'),
('Insulated Flasks'),
('Camping Lights'),
('Portable Showers'),
('Trail Snacks'),
('Hydration Packs'),
('Emergency Blankets'),
('Hammocks'),
('Climbing Gear'),
('Kayaking Gear'),
('Canoeing Gear'),
('Snorkeling Gear'),
('Surfing Gear'),
('Scuba Diving Gear'),
('Swimwear'),
('Swim Caps'),
('Goggles'),
('Floats & Inflatables'),
('Pool Cleaning Tools'),
('Pool Chemicals'),
('Water Toys'),
('Beach Chairs'),
('Sandals & Flip Flops'),
('Rain Gear'),
('Winter Coats'),
('Gloves & Mittens'),
('Scarves & Hats'),
('Snow Boots'),
('Skis & Snowboards'),
('Ski Jackets'),
('Ski Helmets'),
('Ski Gloves'),
('Ski Goggles'),
('Ski Bindings'),
('Snowshoes'),
('Ice Skates'),
('Hockey Gear'),
('Winter Camping Gear'),
('Cold Weather Sleeping Bags'),
('Heated Clothing'),
('Base Layers'),
('Snow Shovels'),
('Ice Scrapers'),
('Salt Spreaders'),
('Winter Tires'),
('Car Covers'),
('Battery Warmers'),
('Heated Seat Cushions'),
('Blankets & Throws'),
('Space Heaters'),
('Fingerless Gloves'),
('Beanies'),
('Ear Muffs'),
('Snow Pants'),
('Winter Jackets'),
('Insulated Boots'),
('Thermal Socks'),
('Moisturizers'),
('Facial Cleansers'),
('Toners'),
('Serums'),
('Face Masks'),
('Eye Creams'),
('Sunscreen'),
('Lip Balms'),
('Acne Treatments'),
('Anti-Aging Products'),
('Natural & Organic Skincare'),
('Men’s Skincare'),
('Exfoliators'),
('Facial Tools'),
('Body Lotions'),
('Body Scrubs'),
('Massage Oils'),
('Stretch Mark Creams'),
('Tanning Products'),
('Hair Shampoos'),
('Conditioners'),
('Hair Masks'),
('Hair Serums'),
('Hair Sprays'),
('Hair Colors'),
('Hair Extensions'),
('Hair Accessories'),
('Hair Dryers'),
('Straighteners'),
('Curling Irons'),
('Styling Tools'),
('Beards & Mustaches'),
('Hair Clippers'),
('Shavers'),
('Pre-Shave Products'),
('Post-Shave Products'),
('Fragrance Sets'),
('Perfume'),
('Colognes'),
('Roll-On Perfumes'),
('Mini Parfumes'),
('Essential Oils'),
('Diffusers'),
('Candles'),
('Air Fresheners'),
('Bath Salts'),
('Body Washes'),
('Shower Gels'),
('Loofahs'),
('Bath Bombs'),
('Bath Oils'),
('Soaps'),
('Face Wash'),
('Deodorants'),
('Antiperspirants'),
('Body Sprays'),
('Shaving Creams'),
('Razors'),
('Shaving Brushes'),
('After Shave'),
('Men’s Grooming Kits'),
('Manicure & Pedicure'),
('Nail Polish'),
('Nail Polish Removers'),
('Cuticle Oils'),
('Nail Files'),
('Manicure Kits'),
('False Nails'),
('Nail Art'),
('Gel Polish'),
('UV Lamps'),
('Nail Glue'),
('Nail Wraps'),
('Press-on Nails'),
('Nail Stickers'),
('Nail Designs'),
('Nail Kits'),
('Foot Creams'),
('Callus Removers'),
('Foot Soaks'),
('Insoles'),
('Orthotics'),
('Foot Massagers'),
('Slippers'),
('Flip Flops'),
('House Shoes'),
('Foot Deodorants'),
('Athletic Footwear'),
('Casual Shoes'),
('Formal Shoes'),
('Boots'),
('Sandals'),
('Shoe Care'),
('Shoelaces'),
('Polishes'),
('Sprays'),
('Cleaners'),
('Protectors'),
('Leather Conditioners'),
('Shoe Horns'),
('Boot Stretchers'),
('Shoe Racks'),
('Shoe Organizers'),
('Travel Shoe Bags'),
('Shoe Boxes'),
('Shoe Inserts'),
('Arch Supports'),
('Heel Liners'),
('Toe Separators'),
('Blisters Pads'),
('Shoe Deodorizers'),
('Odor Absorbers'),
('Womens Footwear'),
('Mens Footwear'),
('Kids Footwear'),
('Toddler Footwear'),
('Infant Footwear'),
('Specialty Footwear'),
('Safety Shoes'),
('Work Boots'),
('Orthopedic Shoes'),
('Diabetic Socks'),
('Compression Socks'),
('Anti-Slip Shoes'),
('Waterproof Shoes'),
('Hiking Shoes'),
('Running Shoes'),
('Training Shoes'),
('Walking Shoes'),
('CrossFit Shoes'),
('Basketball Shoes'),
('Soccer Cleats'),
('Golf Shoes'),
('Tennis Shoes'),
('Cycling Shoes'),
('Skateboarding Shoes'),
('Boxing Shoes'),
('Cheerleading Shoes'),
('Dance Shoes'),
('Figure Skating Boots'),
('Roller Skates'),
('Snowboard Boots'),
('Ski Boots'),
('Water Shoes'),
('Flats'),
('Heels'),
('Wedges'),
('Espadrilles'),
('Mary Janes'),
('Mules'),
('Loafers'),
('Oxfords'),
('Derbies'),
('Boat Shoes'),
('Chelsea Boots'),
('Cowboy Boots'),
('Wellington Boots'),
('Ankle Boots'),
('Knee High Boots'),
('Over the Knee Boots'),
('Platform Shoes'),
('Ballet Flats'),
('Slingbacks'),
('Clogs'),
('Moccasins'),
('Slides');