-- A single SQL INSERT statement to add 200 customer records
INSERT INTO customer (cust_id, cust_password, cust_email, cust_fname, cust_lname, cust_address1, cust_address2, cust_city, cust_prov, cust_country, cust_postal) VALUES
(1, 'pass123!', 'john.smith@example.com', 'John', 'Smith', '123 Maple Street', 'Apt 4B', 'Toronto', 'Ontario', 'Canada', 'M5V 2H1'),
(2, 'janeD_456', 'jane.doe@example.net', 'Jane', 'Doe', '456 Oak Avenue', NULL, 'New York', 'New York', 'USA', '10001'),
(3, 'peterJ#789', 'peter.jones@example.org', 'Peter', 'Jones', '789 Pine Lane', 'Unit 12', 'London', 'Greater London', 'UK', 'SW1A 0AA'),
(4, 'susanB_pass', 'susan.brown@example.com', 'Susan', 'Brown', '101 Elm Court', NULL, 'Sydney', 'New South Wales', 'Australia', '2000'),
(5, 'mikeW2024', 'michael.williams@example.ca', 'Michael', 'Williams', '212 Birch Road', NULL, 'Vancouver', 'British Columbia', 'Canada', 'V6Z 2E6'),
(6, 'emilyG!pWd', 'em.garcia@example.com', 'Emily', 'Garcia', '333 Cedar Blvd', 'Suite 200', 'Los Angeles', 'California', 'USA', '90012'),
(7, 'davidM_sec', 'd.martinez@example.co.uk', 'David', 'Martinez', '444 Spruce Drive', NULL, 'Manchester', 'Greater Manchester', 'UK', 'M1 1AD'),
(8, 'lindaR_111', 'linda.robinson@example.com', 'Linda', 'Robinson', '555 Willow Way', NULL, 'Chicago', 'Illinois', 'USA', '60605'),
(9, 'chrisC_222', 'chris.clark@example.com.au', 'Chris', 'Clark', '666 Acacia Esplanade', 'Level 3', 'Melbourne', 'Victoria', 'Australia', '3000'),
(10, 'patriciaL3', 'patty.lewis@example.com', 'Patricia', 'Lewis', '777 Redwood Path', NULL, 'Houston', 'Texas', 'USA', '77002'),
(11, 'robertH_45', 'rob.hall@example.ca', 'Robert', 'Hall', '888 Juniper Crescent', NULL, 'Montreal', 'Quebec', 'Canada', 'H3B 5J9'),
(12, 'jenniferA_9', 'jen.allen@example.com', 'Jennifer', 'Allen', '999 Sequoia Circle', 'Apt 1', 'Phoenix', 'Arizona', 'USA', '85004'),
(13, 'jamesY_pass', 'james.young@example.org', 'James', 'Young', '111 Aspen Terrace', NULL, 'Philadelphia', 'Pennsylvania', 'USA', '19106'),
(14, 'maryK_word', 'mary.king@example.co.uk', 'Mary', 'King', '222 Holly Green', 'Flat 5C', 'Birmingham', 'West Midlands', 'UK', 'B1 1BB'),
(15, 'danielW_go', 'dan.wright@example.com', 'Daniel', 'Wright', '333 Poplar Place', NULL, 'San Diego', 'California', 'USA', '92101'),
(16, 'barbaraS_7', 'barb.scott@example.ca', 'Barbara', 'Scott', '444 Fir Grove', NULL, 'Calgary', 'Alberta', 'Canada', 'T2P 2M5'),
(17, 'paulG_sec!', 'paul.green@example.com', 'Paul', 'Green', '555 Magnolia Ave', 'Unit 303', 'San Antonio', 'Texas', 'USA', '78205'),
(18, 'nancyA_123', 'nancy.adams@example.com', 'Nancy', 'Adams', '666 Cypress Street', NULL, 'Dallas', 'Texas', 'USA', '75201'),
(19, 'kevinB_456', 'kevin.baker@example.com.au', 'Kevin', 'Baker', '777 Wattle Way', 'Lot 22', 'Perth', 'Western Australia', 'Australia', '6000'),
(20, 'sandraN_78', 'sandra.nelson@example.com', 'Sandra', 'Nelson', '888 Cherry Blossom Rd', NULL, 'San Jose', 'California', 'USA', '95113'),
(21, 'markH_pass', 'mark.hill@example.ca', 'Mark', 'Hill', '999 Hemlock Dr', NULL, 'Ottawa', 'Ontario', 'Canada', 'K1P 1J1'),
(22, 'bettyR_2025', 'betty.ramirez@example.com', 'Betty', 'Ramirez', '1212 Palm Street', 'Ste 10', 'Jacksonville', 'Florida', 'USA', '32202'),
(23, 'stevenC_go', 'steve.campbell@example.com', 'Steven', 'Campbell', '1313 Sycamore Ave', NULL, 'Indianapolis', 'Indiana', 'USA', '46204'),
(24, 'donnaM_sec', 'donna.mitchell@example.co.uk', 'Donna', 'Mitchell', '1414 Rowan Close', NULL, 'Glasgow', 'Scotland', 'UK', 'G1 1RU'),
(25, 'joshP_word', 'josh.perez@example.com', 'Joshua', 'Perez', '1515 Larch Lane', 'Apt 2C', 'Austin', 'Texas', 'USA', '78701'),
(26, 'carolT_112', 'carol.turner@example.com', 'Carol', 'Turner', '1616 Yew Street', NULL, 'Denver', 'Colorado', 'USA', '80202'),
(27, 'jasonP_334', 'jason.parker@example.ca', 'Jason', 'Parker', '1717 Alder Crossing', NULL, 'Edmonton', 'Alberta', 'Canada', 'T5J 2R7'),
(28, 'helenE_556', 'helen.evans@example.com', 'Helen', 'Evans', '1818 Chestnut Blvd', 'Suite 50', 'Seattle', 'Washington', 'USA', '98101'),
(29, 'garyE_778', 'gary.edwards@example.com.au', 'Gary', 'Edwards', '1919 Banksia Court', NULL, 'Brisbane', 'Queensland', 'Australia', '4000'),
(30, 'annaC_990', 'anna.collins@example.com', 'Anna', 'Collins', '2020 Willow Creek Dr', NULL, 'Boston', 'Massachusetts', 'USA', '02108'),
(31, 'brianS_pw1', 'brian.stewart@example.com', 'Brian', 'Stewart', '2121 Birchwood Ave', 'Apt 15', 'Washington', 'D.C.', 'USA', '20001'),
(32, 'sharonM_pw2', 'sharon.morris@example.co.uk', 'Sharon', 'Morris', '2222 Oakwood Terrace', 'Flat 1A', 'Liverpool', 'Merseyside', 'UK', 'L1 8JQ'),
(33, 'keithR_pw3', 'keith.rogers@example.com', 'Keith', 'Rogers', '2323 Pinecrest Rd', NULL, 'Detroit', 'Michigan', 'USA', '48226'),
(34, 'cynthiaR_pw4', 'cindy.reed@example.ca', 'Cynthia', 'Reed', '2424 Maple Leaf Cr', NULL, 'Winnipeg', 'Manitoba', 'Canada', 'R3C 1A1'),
(35, 'larryC_pw5', 'larry.cook@example.com', 'Larry', 'Cook', '2525 Cedar Grove Ln', NULL, 'Charlotte', 'North Carolina', 'USA', '28202'),
(36, 'deborahM_pw6', 'deb.morgan@example.com', 'Deborah', 'Morgan', '2626 Spruce Heights', 'Unit 8', 'Memphis', 'Tennessee', 'USA', '38103'),
(37, 'ronaldB_pw7', 'ron.bell@example.com', 'Ronald', 'Bell', '2727 Redwood Meadows', NULL, 'Baltimore', 'Maryland', 'USA', '21201'),
(38, 'rebeccaP_pw8', 'rebecca.peterson@example.com.au', 'Rebecca', 'Peterson', '2828 Eucalyptus Walk', NULL, 'Adelaide', 'South Australia', 'Australia', '5000'),
(39, 'josephC_pw9', 'joe.cooper@example.com', 'Joseph', 'Cooper', '2929 Aspen Grove', 'Apt 3D', 'Milwaukee', 'Wisconsin', 'USA', '53202'),
(40, 'lauraR_pw10', 'laura.richardson@example.co.uk', 'Laura', 'Richardson', '3030 Holly Bush', NULL, 'Leeds', 'West Yorkshire', 'UK', 'LS1 5AT'),
(41, 'matthewC_pw11', 'matt.cox@example.com', 'Matthew', 'Cox', '3131 Poplar Creek', NULL, 'Portland', 'Oregon', 'USA', '97204'),
(42, 'kimberlyH_pw12', 'kim.howard@example.com', 'Kimberly', 'Howard', '3232 Fir Valley', NULL, 'Las Vegas', 'Nevada', 'USA', '89101'),
(43, 'jerryW_pw13', 'jerry.ward@example.ca', 'Jerry', 'Ward', '3333 Juniper Hills', NULL, 'Quebec City', 'Quebec', 'Canada', 'G1R 4P8'),
(44, 'catherineB_pw14', 'cathy.brooks@example.com', 'Catherine', 'Brooks', '3434 Sequoia Trail', 'Suite 110', 'Oklahoma City', 'Oklahoma', 'USA', '73102'),
(45, 'dennisH_pw15', 'dennis.hayes@example.com', 'Dennis', 'Hayes', '3535 Aspen Ridge', NULL, 'Tucson', 'Arizona', 'USA', '85701'),
(46, 'francesS_pw16', 'fran.simmons@example.com', 'Frances', 'Simmons', '3636 Elmwood Park', NULL, 'Albuquerque', 'New Mexico', 'USA', '87102'),
(47, 'henryW_pw17', 'henry.washington@example.com', 'Henry', 'Washington', '3737 Oakwood Estates', 'Lot 5', 'Fresno', 'California', 'USA', '93721'),
(48, 'janiceF_pw18', 'janice.foster@example.co.uk', 'Janice', 'Foster', '3838 Pine Grove', NULL, 'Sheffield', 'South Yorkshire', 'UK', 'S1 2HH'),
(49, 'walterG_pw19', 'walt.gonzales@example.com', 'Walter', 'Gonzales', '3939 Cedar Point', NULL, 'Sacramento', 'California', 'USA', '95814'),
(50, 'amandaP_pw20', 'amanda.powell@example.ca', 'Amanda', 'Powell', '4040 Birch Hill', 'Unit 7B', 'Halifax', 'Nova Scotia', 'Canada', 'B3H 4R2'),
(51, 'morganRDR2', 'arthur.morgan@example.com', 'Arthur', 'Morgan', '101 Frontier Way', NULL, 'Valentine', 'New Hanover', 'USA', '54321'),
(52, 'chenD#52', 'david.chen@example.co.uk', 'David', 'Chen', '88 Baker Street', 'Flat 7', 'London', 'Greater London', 'UK', 'NW1 6XE'),
(53, 'sjohnson!24', 'sarah.j@example.ca', 'Sarah', 'Johnson', '255 Granville St', 'Suite 800', 'Vancouver', 'British Columbia', 'Canada', 'V6C 1S4'),
(54, 'emilyT_aus', 'emily.taylor@example.com.au', 'Emily', 'Taylor', '42 Wallaby Way', NULL, 'Sydney', 'New South Wales', 'Australia', '2000'),
(55, 'rodriguezF55', 'fernando.r@example.com', 'Fernando', 'Rodriguez', 'Calle Principal 45', 'Apto 2', 'Madrid', 'Community of Madrid', 'Spain', '28001'),
(56, 'nguyenT_56', 'trang.nguyen@example.com.vn', 'Trang', 'Nguyen', '123 Pho Hue', NULL, 'Hanoi', 'Hoan Kiem', 'Vietnam', '100000'),
(57, 'kimS_korea', 'sung.kim@example.co.kr', 'Sung-ho', 'Kim', '45 Gangnam-daero', 'Floor 12', 'Seoul', 'Seoul', 'South Korea', '06130'),
(58, 'mullerH_de', 'hans.muller@example.de', 'Hans', 'Müller', 'Hauptstraße 10', NULL, 'Berlin', 'Berlin', 'Germany', '10115'),
(59, 'garciaM_mex', 'maria.garcia@example.com.mx', 'Maria', 'Garcia', 'Avenida Reforma 222', NULL, 'Mexico City', 'CDMX', 'Mexico', '06600'),
(60, 'silvaJ_br', 'joao.silva@example.com.br', 'João', 'Silva', 'Rua Augusta 500', 'Andar 3', 'São Paulo', 'SP', 'Brazil', '01304-000'),
(61, 'patelA_in', 'aisha.patel@example.in', 'Aisha', 'Patel', '7 MG Road', NULL, 'Mumbai', 'Maharashtra', 'India', '400001'),
(62, 'rossiG_it', 'giulia.rossi@example.it', 'Giulia', 'Rossi', 'Via del Corso 1', NULL, 'Rome', 'Lazio', 'Italy', '00186'),
(63, 'smithJ_za', 'john.smith@example.co.za', 'John', 'Smith', '24 Long Street', 'Office 3', 'Cape Town', 'Western Cape', 'South Africa', '8001'),
(64, 'anderssonL_se', 'lars.andersson@example.se', 'Lars', 'Andersson', 'Drottninggatan 89', NULL, 'Stockholm', 'Stockholm', 'Sweden', '111 60'),
(65, 'ivanovD_ru', 'dmitri.ivanov@example.ru', 'Dmitri', 'Ivanov', 'Tverskaya Street 4', NULL, 'Moscow', 'Moscow', 'Russia', '125009'),
(66, 'li_wei_cn', 'wei.li@example.cn', 'Wei', 'Li', '10 Fuxingmen Inner St', NULL, 'Beijing', 'Beijing', 'China', '100031'),
(67, 'duboisM_fr', 'manon.dubois@example.fr', 'Manon', 'Dubois', '25 Rue de Rivoli', NULL, 'Paris', 'Île-de-France', 'France', '75004'),
(68, 'satoK_jp', 'kenji.sato@example.co.jp', 'Kenji', 'Sato', '1-1-2 Oshiage', 'Apt 101', 'Sumida', 'Tokyo', 'Japan', '131-0045'),
(69, 'abadiA_eg', 'ahmed.abadi@example.com.eg', 'Ahmed', 'Abadi', '15 Tahrir Square', NULL, 'Cairo', 'Cairo', 'Egypt', '11511'),
(70, 'oconnorS_ie', 'sean.oconnor@example.ie', 'Sean', 'O''Connor', '42 O''Connell Street', NULL, 'Dublin', 'Dublin', 'Ireland', 'D01 F5P2'),
(71, 'vanderL_nl', 'liesje.vanderberg@example.nl', 'Liesje', 'van der Berg', 'Damrak 28', '3rd Floor', 'Amsterdam', 'North Holland', 'Netherlands', '1012 LJ'),
(72, 'jensenM_dk', 'mette.jensen@example.dk', 'Mette', 'Jensen', 'Vestergade 11', NULL, 'Copenhagen', 'Capital Region', 'Denmark', '1456'),
(73, 'korhonenA_fi', 'antti.korhonen@example.fi', 'Antti', 'Korhonen', 'Mannerheimintie 5', NULL, 'Helsinki', 'Uusimaa', 'Finland', '00100'),
(74, 'papadopoulosN_gr', 'nikos.p@example.gr', 'Nikos', 'Papadopoulos', 'Ermou Street 30', NULL, 'Athens', 'Attica', 'Greece', '105 63'),
(75, 'fernandezJ_ar', 'javier.fernandez@example.com.ar', 'Javier', 'Fernandez', 'Avenida 9 de Julio', NULL, 'Buenos Aires', 'CABA', 'Argentina', 'C1043'),
(76, 'olsonE_no', 'erik.olson@example.no', 'Erik', 'Olson', 'Karl Johans gate 22', NULL, 'Oslo', 'Oslo', 'Norway', '0159'),
(77, 'nowakP_pl', 'piotr.nowak@example.pl', 'Piotr', 'Nowak', 'ul. Marszałkowska 100', 'Apt 5', 'Warsaw', 'Masovia', 'Poland', '00-011'),
(78, 'horvathK_hu', 'katalin.h@example.hu', 'Katalin', 'Horvath', 'Andrássy út 2', NULL, 'Budapest', 'Budapest', 'Hungary', '1061'),
(79, 'costaM_pt', 'miguel.costa@example.pt', 'Miguel', 'Costa', 'Avenida da Liberdade 150', NULL, 'Lisbon', 'Lisbon', 'Portugal', '1250-146'),
(80, 'bergerF_at', 'franz.berger@example.at', 'Franz', 'Berger', 'Kärntner Straße 30', NULL, 'Vienna', 'Vienna', 'Austria', '1010'),
(81, 'lee_h_tw', 'hsiao.lee@example.com.tw', 'Hsiao-Ling', 'Lee', 'No. 5, Section 5, Xinyi Road', NULL, 'Taipei', 'Taipei', 'Taiwan', '110'),
(82, 'tanC_sg', 'chloe.tan@example.com.sg', 'Chloe', 'Tan', '1 Orchard Road', '#05-12', 'Singapore', 'Singapore', 'Singapore', '238824'),
(83, 'chukwuA_ng', 'amara.chukwu@example.com.ng', 'Amara', 'Chukwu', '100 Awolowo Road', NULL, 'Lagos', 'Lagos', 'Nigeria', '101233'),
(84, 'almeidaS_cl', 'sofia.almeida@example.cl', 'Sofia', 'Almeida', 'Apoquindo 3000', 'Piso 10', 'Santiago', 'Metropolitan Region', 'Chile', '7550000'),
(85, 'yılmazM_tr', 'mehmet.yilmaz@example.com.tr', 'Mehmet', 'Yılmaz', 'İstiklal Caddesi 50', NULL, 'Istanbul', 'Istanbul', 'Turkey', '34435'),
(86, 'gomezL_co', 'lucas.gomez@example.co', 'Lucas', 'Gomez', 'Carrera 7 # 12-45', NULL, 'Bogotá', 'Bogotá D.C.', 'Colombia', '111711'),
(87, 'reidA_nz', 'aisha.reid@example.co.nz', 'Aisha', 'Reid', '155 Queen Street', NULL, 'Auckland', 'Auckland', 'New Zealand', '1010'),
(88, 'schmidtK_ch', 'klaus.schmidt@example.ch', 'Klaus', 'Schmidt', 'Bahnhofstrasse 70', NULL, 'Zurich', 'Zurich', 'Switzerland', '8001'),
(89, 'limJ_my', 'jason.lim@example.com.my', 'Jason', 'Lim', '5 Jalan Ampang', NULL, 'Kuala Lumpur', 'Kuala Lumpur', 'Malaysia', '50450'),
(90, 'novotnyJ_cz', 'jana.novotny@example.cz', 'Jana', 'Novotný', 'Václavské náměstí 20', NULL, 'Prague', 'Prague', 'Czech Republic', '110 00'),
(91, 'petrovV_bg', 'vasil.petrov@example.bg', 'Vasil', 'Petrov', 'Vitosha Boulevard 60', NULL, 'Sofia', 'Sofia City', 'Bulgaria', '1000'),
(92, 'ionescuA_ro', 'andrei.ionescu@example.ro', 'Andrei', 'Ionescu', 'Calea Victoriei 10', NULL, 'Bucharest', 'Bucharest', 'Romania', '010062'),
(93, 'wongC_hk', 'chris.wong@example.com.hk', 'Chris', 'Wong', '20 Nathan Road', '15/F', 'Hong Kong', 'Kowloon', 'Hong Kong', 'T2P 2H6'),
(94, 'hernandezC_pe', 'carlos.h@example.com.pe', 'Carlos', 'Hernandez', 'Jirón de la Unión 500', NULL, 'Lima', 'Lima', 'Peru', 'LIMA 1'),
(95, 'gonzalezS_uy', 'santiago.g@example.com.uy', 'Santiago', 'Gonzalez', 'Avenida 18 de Julio 1234', NULL, 'Montevideo', 'Montevideo', 'Uruguay', '11200'),
(96, 'davisB_jm', 'benjamin.davis@example.com.jm', 'Benjamin', 'Davis', '9 Knutsford Blvd', NULL, 'Kingston', 'Saint Andrew', 'Jamaica', 'KIN 5'),
(97, 'martinsF_ao', 'fabio.martins@example.co.ao', 'Fábio', 'Martins', 'Avenida 4 de Fevereiro', NULL, 'Luanda', 'Luanda', 'Angola', '10101'),
(98, 'aliO_ae', 'omar.ali@example.ae', 'Omar', 'Ali', 'Sheikh Zayed Road', 'Tower 1, Apt 2020', 'Dubai', 'Dubai', 'UAE', '00000'),
(99, 'khanF_pk', 'fatima.khan@example.com.pk', 'Fatima', 'Khan', 'M. A. Jinnah Road', NULL, 'Karachi', 'Sindh', 'Pakistan', '74200'),
(100, 'bauerL_de', 'lena.bauer@example.de', 'Lena', 'Bauer', 'Schillerstraße 5', NULL, 'Munich', 'Bavaria', 'Germany', '80336'),
(101, 'thompsonA', 'alice.t@example.com', 'Alice', 'Thompson', '10 Downing Street', NULL, 'London', 'Greater London', 'UK', 'SW1A 2AA'),
(102, 'garciaM', 'miguel.g@example.com', 'Miguel', 'Garcia', '200 Park Avenue', 'Floor 10', 'New York', 'New York', 'USA', '10166'),
(103, 'ivanovaE', 'elena.i@example.ru', 'Elena', 'Ivanova', 'Nevsky Prospekt 12', NULL, 'Saint Petersburg', 'Saint Petersburg', 'Russia', '191186'),
(104, 'chenL', 'li.chen@example.cn', 'Li', 'Chen', 'West Nanjing Road 500', NULL, 'Shanghai', 'Shanghai', 'China', '200041'),
(105, 'kobayashiY', 'yuki.k@example.co.jp', 'Yuki', 'Kobayashi', 'Shibuya Crossing', 'Hachi Bldg', 'Shibuya', 'Tokyo', 'Japan', '150-0042'),
(106, 'singhR', 'rohan.s@example.in', 'Rohan', 'Singh', 'Connaught Place', 'Block A', 'New Delhi', 'Delhi', 'India', '110001'),
(107, 'williamsO', 'olivia.w@example.com.au', 'Olivia', 'Williams', '300 Bourke Street', NULL, 'Melbourne', 'Victoria', 'Australia', '3000'),
(108, 'brownC', 'charlie.b@example.ca', 'Charlie', 'Brown', '1 Bloor Street East', 'Suite 500', 'Toronto', 'Ontario', 'Canada', 'M4W 1A9'),
(109, 'jonesS', 'sophia.j@example.co.uk', 'Sophia', 'Jones', '5 Princess Street', NULL, 'Manchester', 'Greater Manchester', 'UK', 'M2 4DF'),
(110, 'millerJ', 'jack.m@example.de', 'Jack', 'Miller', 'Friedrichstraße 100', NULL, 'Berlin', 'Berlin', 'Germany', '10117'),
(111, 'davisE', 'ethan.d@example.com', 'Ethan', 'Davis', '1 Rodeo Drive', NULL, 'Beverly Hills', 'California', 'USA', '90210'),
(112, 'rodriguezI', 'isabella.r@example.com.mx', 'Isabella', 'Rodriguez', 'Paseo de la Castellana 80', NULL, 'Madrid', 'Community of Madrid', 'Spain', '28046'),
(113, 'martinezL', 'liam.m@example.com.ar', 'Liam', 'Martinez', 'Caminito', NULL, 'Buenos Aires', 'CABA', 'Argentina', 'C1157'),
(114, 'hernandezC', 'chloe.h@example.com', 'Chloe', 'Hernandez', 'Copacabana Beach', 'Posto 5', 'Rio de Janeiro', 'RJ', 'Brazil', '22070-011'),
(115, 'lopezM', 'mia.l@example.it', 'Mia', 'Lopez', 'Piazza San Marco 1', NULL, 'Venice', 'Veneto', 'Italy', '30124'),
(116, 'gonzalezA', 'ava.g@example.fr', 'Ava', 'Gonzalez', 'Champs-Élysées 101', NULL, 'Paris', 'Île-de-France', 'France', '75008'),
(117, 'perezN', 'noah.p@example.com', 'Noah', 'Perez', 'La Rambla 50', NULL, 'Barcelona', 'Catalonia', 'Spain', '08002'),
(118, 'sanchezJ', 'james.s@example.com', 'James', 'Sanchez', 'Hollywood Walk of Fame', NULL, 'Los Angeles', 'California', 'USA', '90028'),
(119, 'ramirezO', 'oliver.r@example.com', 'Oliver', 'Ramirez', 'Golden Gate Bridge', NULL, 'San Francisco', 'California', 'USA', '94129'),
(120, 'torresE', 'evelyn.t@example.com', 'Evelyn', 'Torres', 'Statue of Liberty', NULL, 'New York', 'New York', 'USA', '10004'),
(121, 'floresA', 'amelia.f@example.com', 'Amelia', 'Flores', 'CN Tower', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 2T6'),
(122, 'riveraL', 'lucas.r@example.com', 'Lucas', 'Rivera', 'Sydney Opera House', NULL, 'Sydney', 'New South Wales', 'Australia', '2000'),
(123, 'gomezW', 'william.g@example.com', 'William', 'Gomez', 'Eiffel Tower', NULL, 'Paris', 'Île-de-France', 'France', '75007'),
(124, 'diazB', 'benjamin.d@example.com', 'Benjamin', 'Diaz', 'Colosseum', NULL, 'Rome', 'Lazio', 'Italy', '00184'),
(125, 'reyesH', 'harper.r@example.com', 'Harper', 'Reyes', 'Acropolis', NULL, 'Athens', 'Attica', 'Greece', '105 58'),
(126, 'cruzC', 'charlotte.c@example.com', 'Charlotte', 'Cruz', 'Red Square', NULL, 'Moscow', 'Moscow', 'Russia', '109012'),
(127, 'ortizS', 'sebastian.o@example.com', 'Sebastian', 'Ortiz', 'Forbidden City', NULL, 'Beijing', 'Beijing', 'China', '100009'),
(128, 'gutierrezA', 'abigail.g@example.com', 'Abigail', 'Gutierrez', 'Taj Mahal', NULL, 'Agra', 'Uttar Pradesh', 'India', '282001'),
(129, 'jimenezM', 'madison.j@example.com', 'Madison', 'Jimenez', 'Pyramids of Giza', NULL, 'Giza', 'Giza', 'Egypt', '12556'),
(130, 'morenoE', 'ella.m@example.com', 'Ella', 'Moreno', 'Machu Picchu', NULL, 'Cusco', 'Cusco', 'Peru', '08000'),
(131, 'castilloL', 'logan.c@example.com', 'Logan', 'Castillo', 'Christ the Redeemer', NULL, 'Rio de Janeiro', 'RJ', 'Brazil', '22241-330'),
(132, 'romeroG', 'grace.r@example.com', 'Grace', 'Romero', 'Burj Khalifa', NULL, 'Dubai', 'Dubai', 'UAE', '00000'),
(133, 'mendozaV', 'victoria.m@example.com', 'Victoria', 'Mendoza', 'Great Wall of China', NULL, 'Huairou', 'Beijing', 'China', '101405'),
(134, 'alvarezR', 'riley.a@example.com', 'Riley', 'Alvarez', 'Petra', NULL, 'Wadi Musa', 'Ma''an', 'Jordan', '71810'),
(135, 'ruizZ', 'zoey.r@example.com', 'Zoey', 'Ruiz', 'Chichen Itza', NULL, 'Tinúm', 'Yucatán', 'Mexico', '97751'),
(136, 'vargasP', 'penelope.v@example.com', 'Penelope', 'Vargas', 'Angkor Wat', NULL, 'Siem Reap', 'Siem Reap', 'Cambodia', '17252'),
(137, 'medinaA', 'aiden.m@example.com', 'Aiden', 'Medina', 'Stonehenge', NULL, 'Amesbury', 'Wiltshire', 'UK', 'SP4 7DE'),
(138, 'sotoL', 'layla.s@example.com', 'Layla', 'Soto', 'Neuschwanstein Castle', NULL, 'Schwangau', 'Bavaria', 'Germany', '87645'),
(139, 'castroN', 'nora.c@example.com', 'Nora', 'Castro', 'Santorini', NULL, 'Oia', 'South Aegean', 'Greece', '84702'),
(140, 'aguilarL', 'lillian.a@example.com', 'Lillian', 'Aguilar', 'Mount Fuji', NULL, 'Fujinomiya', 'Shizuoka', 'Japan', '418-0000'),
(141, 'moralesH', 'hannah.m@example.com', 'Hannah', 'Morales', 'Serengeti National Park', NULL, 'Seronera', 'Arusha', 'Tanzania', '23102'),
(142, 'guzmanA', 'addison.g@example.com', 'Addison', 'Guzman', 'Galapagos Islands', NULL, 'Puerto Ayora', 'Galápagos', 'Ecuador', '200350'),
(143, 'penaE', 'eleanor.p@example.com', 'Eleanor', 'Pena', 'Iguazu Falls', NULL, 'Foz do Iguaçu', 'Paraná', 'Brazil', '85853-830'),
(144, 'delgadoS', 'stella.d@example.com', 'Stella', 'Delgado', 'Victoria Falls', NULL, 'Livingstone', 'Southern Province', 'Zambia', '10101'),
(145, 'riosN', 'natalie.r@example.com', 'Natalie', 'Rios', 'Ha Long Bay', NULL, 'Ha Long', 'Quảng Ninh', 'Vietnam', '200000'),
(146, 'vegaA', 'aubrey.v@example.com', 'Aubrey', 'Vega', 'Pamukkale', NULL, 'Denizli', 'Denizli', 'Turkey', '20280'),
(147, 'leonZ', 'zachary.l@example.com', 'Zachary', 'Leon', 'Bora Bora', NULL, 'Vaitape', 'Leeward Islands', 'French Polynesia', '98730'),
(148, 'santosI', 'isaac.s@example.com', 'Isaac', 'Santos', 'Maldives', NULL, 'Malé', 'Kaafu Atoll', 'Maldives', '20002'),
(149, 'juarezE', 'eli.j@example.com', 'Eli', 'Juarez', 'Fiji', NULL, 'Suva', 'Central Division', 'Fiji', '0000'),
(150, 'maldonadoC', 'christopher.m@example.com', 'Christopher', 'Maldonado', 'Grand Canyon', NULL, 'Grand Canyon Village', 'Arizona', 'USA', '86023'),
(151, 'nuñezJ', 'joshua.n@example.com', 'Joshua', 'Nuñez', 'Yellowstone National Park', NULL, 'Yellowstone', 'Wyoming', 'USA', '82190'),
(152, 'salazarA', 'andrew.s@example.com', 'Andrew', 'Salazar', 'Yosemite National Park', NULL, 'Yosemite Valley', 'California', 'USA', '95389'),
(153, 'mercadoL', 'lincoln.m@example.com', 'Lincoln', 'Mercado', 'Zion National Park', NULL, 'Springdale', 'Utah', 'USA', '84767'),
(154, 'benitezM', 'mateo.b@example.com', 'Mateo', 'Benitez', 'Banff National Park', NULL, 'Banff', 'Alberta', 'Canada', 'T1L 1K2'),
(155, 'padillaJ', 'julian.p@example.com', 'Julian', 'Padilla', 'Jasper National Park', NULL, 'Jasper', 'Alberta', 'Canada', 'T0E 1E0'),
(156, 'acostaL', 'leo.a@example.com', 'Leo', 'Acosta', 'Torres del Paine', NULL, 'Puerto Natales', 'Magallanes', 'Chile', '6160000'),
(157, 'mejiaA', 'aaron.m@example.com', 'Aaron', 'Mejia', 'Patagonia', NULL, 'El Calafate', 'Santa Cruz', 'Argentina', 'Z9405'),
(158, 'herreraC', 'connor.h@example.com', 'Connor', 'Herrera', 'Amazon Rainforest', NULL, 'Manaus', 'Amazonas', 'Brazil', '69005-040'),
(159, 'cabreraK', 'kevin.c@example.com', 'Kevin', 'Cabrera', 'Sahara Desert', NULL, 'Merzouga', 'Drâa-Tafilalet', 'Morocco', '52202'),
(160, 'davilaT', 'thomas.d@example.com', 'Thomas', 'Davila', 'Antarctica', NULL, 'McMurdo Station', 'Ross Dependency', 'Antarctica', '96599'),
(161, 'pinedaJ', 'jaxon.p@example.com', 'Jaxon', 'Pineda', 'Arctic Circle', NULL, 'Tromsø', 'Troms og Finnmark', 'Norway', '9008'),
(162, 'roblesC', 'caleb.r@example.com', 'Caleb', 'Robles', 'Mount Everest', NULL, 'Tingri', 'Xigazê', 'China', '858200'),
(163, 'solisJ', 'josiah.s@example.com', 'Josiah', 'Solis', 'K2', NULL, 'Shigar', 'Gilgit-Baltistan', 'Pakistan', '16300'),
(164, 'marquezC', 'charles.m@example.com', 'Charles', 'Marquez', 'Mariana Trench', NULL, 'Challenger Deep', 'Pacific Ocean', 'Federated States of Micronesia', '96940'),
(165, 'camposI', 'isla.c@example.com', 'Isla', 'Campos', 'Nile River', NULL, 'Aswan', 'Aswan', 'Egypt', '81511'),
(166, 'montoyaE', 'emilia.m@example.com', 'Emilia', 'Montoya', 'Ganges River', NULL, 'Varanasi', 'Uttar Pradesh', 'India', '221001'),
(167, 'velasquezL', 'luna.v@example.com', 'Luna', 'Velasquez', 'Yangtze River', NULL, 'Yichang', 'Hubei', 'China', '443000'),
(168, 'figueroaA', 'aurora.f@example.com', 'Aurora', 'Figueroa', 'Mississippi River', NULL, 'New Orleans', 'Louisiana', 'USA', '70130'),
(169, 'gallegosC', 'claire.g@example.com', 'Claire', 'Gallegos', 'Danube River', NULL, 'Budapest', 'Budapest', 'Hungary', '1013'),
(170, 'valenciaB', 'bella.v@example.com', 'Bella', 'Valencia', 'Volga River', NULL, 'Volgograd', 'Volgograd Oblast', 'Russia', '400066'),
(171, 'ayalaS', 'skylar.a@example.com', 'Skylar', 'Ayala', 'Mekong River', NULL, 'Can Tho', 'Can Tho', 'Vietnam', '900000'),
(172, 'mirandaP', 'piper.m@example.com', 'Piper', 'Miranda', 'Lake Superior', NULL, 'Duluth', 'Minnesota', 'USA', '55802'),
(173, 'sandovalE', 'eva.s@example.com', 'Eva', 'Sandoval', 'Lake Victoria', NULL, 'Mwanza', 'Mwanza', 'Tanzania', '33112'),
(174, 'rochaS', 'sadie.r@example.com', 'Sadie', 'Rocha', 'Caspian Sea', NULL, 'Baku', 'Absheron', 'Azerbaijan', 'AZ1000'),
(175, 'barreraA', 'anna.b@example.com', 'Anna', 'Barrera', 'Baikal Lake', NULL, 'Irkutsk', 'Irkutsk Oblast', 'Russia', '664003'),
(176, 'ibarraL', 'leah.i@example.com', 'Leah', 'Ibarra', 'Great Barrier Reef', NULL, 'Cairns', 'Queensland', 'Australia', '4870'),
(177, 'valdezA', 'ariana.v@example.com', 'Ariana', 'Valdez', 'Dead Sea', NULL, 'Ein Bokek', 'Southern District', 'Palestine', '8693000'),
(178, 'cardenasA', 'allison.c@example.com', 'Allison', 'Cardenas', 'Salarde Uyuni', NULL, 'Uyuni', 'Potosí', 'Bolivia', '09-0101-01'),
(179, 'francoS', 'savannah.f@example.com', 'Savannah', 'Franco', 'Atacama Desert', NULL, 'San Pedro de Atacama', 'Antofagasta', 'Chile', '1410000'),
(180, 'tapiaB', 'brooklyn.t@example.com', 'Brooklyn', 'Tapia', 'Gobi Desert', NULL, 'Dalanzadgad', 'Ömnögovi', 'Mongolia', '47016'),
(181, 'beltranA', 'audrey.b@example.com', 'Audrey', 'Beltran', 'Kalahari Desert', NULL, 'Ghanzi', 'Ghanzi District', 'Botswana', '21'),
(182, 'espinozaS', 'serenity.e@example.com', 'Serenity', 'Espinoza', 'Siberia', NULL, 'Yakutsk', 'Sakha Republic', 'Russia', '677000'),
(183, 'lugoH', 'hazel.l@example.com', 'Hazel', 'Lugo', 'The Outback', NULL, 'Alice Springs', 'Northern Territory', 'Australia', '0870'),
(184, 'salasV', 'violet.s@example.com', 'Violet', 'Salas', 'The Alps', NULL, 'Chamonix', 'Haute-Savoie', 'France', '74400'),
(185, 'montesG', 'genesis.m@example.com', 'Genesis', 'Montes', 'The Himalayas', NULL, 'Kathmandu', 'Bagmati', 'Nepal', '44600'),
(186, 'serranoS', 'scarlett.s@example.com', 'Scarlett', 'Serrano', 'The Andes', NULL, 'Huaraz', 'Ancash', 'Peru', '02001'),
(187, 'duarteA', 'aria.d@example.com', 'Aria', 'Duarte', 'Rocky Mountains', NULL, 'Aspen', 'Colorado', 'USA', '81611'),
(188, 'zamoraN', 'nova.z@example.com', 'Nova', 'Zamora', 'Ural Mountains', NULL, 'Yekaterinburg', 'Sverdlovsk Oblast', 'Russia', '620014'),
(189, 'parraE', 'ellie.p@example.com', 'Ellie', 'Parra', 'Appalachian Mountains', NULL, 'Asheville', 'North Carolina', 'USA', '28801'),
(190, 'orozcoM', 'mila.o@example.com', 'Mila', 'Orozco', 'Trans-Siberian Railway', NULL, 'Vladivostok', 'Primorsky Krai', 'Russia', '690091'),
(191, 'arellanoP', 'paisley.a@example.com', 'Paisley', 'Arellano', 'Route 66', NULL, 'Amarillo', 'Texas', 'USA', '79101'),
(192, 'gallardoE', 'everly.g@example.com', 'Everly', 'Gallardo', 'Silk Road', NULL, 'Samarkand', 'Samarkand', 'Uzbekistan', '140100'),
(193, 'rendonI', 'isabelle.r@example.com', 'Isabelle', 'Rendon', 'Inca Trail', NULL, 'Aguas Calientes', 'Cusco', 'Peru', '08681'),
(194, 'escobarK', 'kennedy.e@example.com', 'Kennedy', 'Escobar', 'Orient Express', NULL, 'Venice', 'Veneto', 'Italy', '30100'),
(195, 'villarrealL', 'lucy.v@example.com', 'Lucy', 'Villarreal', 'Pacific Crest Trail', NULL, 'Campo', 'California', 'USA', '91906'),
(196, 'roldanC', 'clara.r@example.com', 'Clara', 'Roldan', 'Camino de Santiago', NULL, 'Santiago de Compostela', 'Galicia', 'Spain', '15705'),
(197, 'pachecoR', 'ruby.p@example.com', 'Ruby', 'Pacheco', 'Autobahn', NULL, 'Frankfurt', 'Hesse', 'Germany', '60311'),
(198, 'maciasT', 'taylor.m@example.com', 'Taylor', 'Macias', 'Shinkansen', NULL, 'Kyoto', 'Kyoto', 'Japan', '600-8216'),
(199, 'contrerasN', 'naomi.c@example.com', 'Naomi', 'Contreras', 'Pan-American Highway', NULL, 'Prudhoe Bay', 'Alaska', 'USA', '99734'),
(200, 'zunigaJ', 'josephine.z@example.com', 'Josephine', 'Zuniga', 'Grand Trunk Road', NULL, 'Kolkata', 'West Bengal', 'India', '700001');
